from __future__ import annotations


YES_NO_REVIEW = ("Sí", "No", "A revisar")
REGISTRATION = ("Sí", "No", "En trámite", "Baja", "A revisar", "No corresponde")
CONTROL = ("OK", "Pendiente", "Con diferencias", "A revisar")


RESPONSIBLE_PROFILE_SECTIONS = (
    ("Datos generales del régimen", (
        ("ri_inscripto", "Está inscripto como Responsable Inscripto", REGISTRATION),
        ("ri_fecha_alta", "Fecha de alta como Responsable Inscripto", "date"),
        ("ri_fecha_inicio", "Fecha de inicio de actividades", "date"),
        ("ri_fecha_baja", "Fecha de baja", "date"),
        ("ri_motivo_alta", "Motivo de alta", ("Inicio de actividad", "Exclusión de monotributo", "Renuncia al monotributo", "Pase voluntario a régimen general", "Alta de sociedad", "Regularización fiscal", "Otro", "A revisar")),
        ("ri_condicion_iva", "Condición frente al IVA", ("Responsable Inscripto", "Exento", "No alcanzado", "Monotributista excluido", "A revisar", "Otro")),
        ("ri_condicion_ganancias", "Condición frente a Ganancias", ("Ganancias Personas Humanas", "Ganancias Sociedades", "Exento", "No inscripto", "A revisar", "Otro")),
        ("ri_condicion_autonomos", "Condición frente a Autónomos", ("Inscripto", "No inscripto", "Exento", "Relación de dependencia simultánea", "Jubilado", "Director / socio gerente", "A revisar", "No corresponde")),
        ("ri_tipo_contribuyente", "Tipo de contribuyente", ("Persona humana", "Sociedad", "Sucesión indivisa", "Asociación", "Fundación", "Otro")),
        ("ri_actividad_principal", "Actividad principal", "text"),
        ("ri_codigo_actividad", "Código de actividad", "digits"),
        ("ri_actividades_secundarias", "Actividades secundarias", "text"),
        ("ri_observaciones", "Observaciones generales", "text"),
    )),
    ("IVA", (
        ("iva_alta", "Alta en IVA", REGISTRATION),
        ("iva_fecha_alta", "Fecha de alta en IVA", "date"),
        ("iva_fecha_baja", "Fecha de baja en IVA", "date"),
        ("iva_periodicidad", "Periodicidad", ("Mensual", "Otro", "No corresponde")),
        ("iva_libro_digital", "Libro IVA Digital", ("Activo", "No activo", "Presentado", "Pendiente", "Vencido", "A revisar", "No corresponde")),
        ("iva_ultimo_presentado", "Último período IVA presentado", "period"),
        ("iva_ultimo_controlado", "Último período IVA controlado", "period"),
        ("iva_saldo_tecnico", "Tiene saldo técnico a favor", YES_NO_REVIEW),
        ("iva_libre_disponibilidad", "Tiene saldo de libre disponibilidad", YES_NO_REVIEW),
        ("iva_retenciones", "Tiene retenciones IVA", YES_NO_REVIEW),
        ("iva_percepciones", "Tiene percepciones IVA", YES_NO_REVIEW),
        ("iva_alicuotas", "Alícuotas habituales de IVA", ("multi", "21%", "10,5%", "27%", "Exento", "No gravado", "Mixto", "A revisar")),
        ("iva_observaciones", "Observaciones IVA", "text"),
    )),
    ("Ganancias", (
        ("gan_inscripto", "Inscripto en Ganancias", REGISTRATION),
        ("gan_fecha_alta", "Fecha de alta en Ganancias", "date"),
        ("gan_tipo", "Tipo de Ganancias", ("Personas Humanas", "Sociedades", "Exento", "No corresponde", "A revisar")),
        ("gan_regimen", "Régimen", ("Régimen general", "Ganancias simplificada", "Otro", "A revisar")),
        ("gan_cierre", "Cierre de ejercicio", "date"),
        ("gan_anticipos", "Anticipos", ("Sí", "No", "A revisar", "No corresponde")),
        ("gan_ultima_ddjj", "Última DDJJ presentada", "year"),
        ("gan_deducciones", "Deducciones informadas", ("Sí", "No", "Parcial", "A revisar", "No corresponde")),
        ("gan_cargas_familia", "Cargas de familia", ("Sí", "No", "A revisar", "No corresponde")),
        ("gan_empleados", "Tiene empleados en relación de dependencia", YES_NO_REVIEW),
        ("gan_otras_fuentes", "Tiene ingresos de otras fuentes", YES_NO_REVIEW),
        ("gan_observaciones", "Observaciones Ganancias", "text"),
    )),
    ("Autónomos", (
        ("aut_inscripto", "Inscripto en Autónomos", REGISTRATION),
        ("aut_fecha_alta", "Fecha de alta en Autónomos", "date"),
        ("aut_fecha_baja", "Fecha de baja en Autónomos", "date"),
        ("aut_categoria", "Categoría autónomo", ("I", "II", "III", "IV", "V", "A revisar", "No corresponde")),
        ("aut_tabla", "Tabla", ("Tabla I", "Tabla II", "Tabla III", "Tabla IV", "Otra", "A revisar", "No corresponde")),
        ("aut_condicion", "Condición", ("Trabajador autónomo", "Director", "Socio gerente", "Pluriactividad", "Jubilado", "Relación de dependencia simultánea", "Otro", "A revisar")),
        ("aut_reduccion", "Reducción por pluriactividad", ("Sí", "No", "A revisar", "No corresponde")),
        ("aut_ultimo_pago", "Último período pagado", "period"),
        ("aut_observaciones", "Observaciones Autónomos", "text"),
    )),
    ("Facturación", (
        ("fac_comprobantes", "Tipos de comprobantes habilitados", ("multi", "Factura A", "Factura B", "Factura E", "Factura M", "Nota de crédito A", "Nota de crédito B", "Nota de crédito E", "Nota de débito A", "Nota de débito B", "Recibo", "Otro")),
        ("fac_a_autorizada", "Factura A autorizada", ("Sí", "No", "En trámite", "Factura M", "A revisar", "No corresponde")),
        ("fac_fecha_a", "Fecha de autorización Factura A", "date"),
        ("fac_m", "Tiene Factura M", YES_NO_REVIEW),
        ("fac_puntos_venta", "Puntos de venta activos", "text"),
        ("fac_sistema", "Sistema de facturación", ("ARCA Comprobantes en Línea", "Facturador móvil", "Sistema propio", "Sistema de gestión", "Marketplace", "Otro")),
        ("fac_correlatividad", "Control de correlatividad", CONTROL),
        ("fac_usd", "Emite comprobantes en USD", ("Sí", "No", "Ocasional", "A revisar")),
        ("fac_e", "Emite Factura E", ("Sí", "No", "En trámite", "A revisar")),
        ("fac_observaciones", "Observaciones de facturación", "text"),
    )),
    ("Compras y ventas", (
        ("cv_fuentes_ventas", "Fuentes principales de ventas", ("multi", "ARCA", "Mercado Libre", "Mercado Pago", "Tienda Nube", "Local físico", "Transferencias", "Sistema de gestión", "Otro")),
        ("cv_fuentes_compras", "Fuentes principales de compras", ("multi", "ARCA", "Proveedores", "Mercado Libre", "Extractos bancarios", "Sistema de gestión", "Otro")),
        ("cv_periodicidad", "Periodicidad de control", ("Mensual", "Quincenal", "Semanal", "A requerimiento", "Otro")),
        ("cv_ventas_arca", "Control ventas vs ARCA", CONTROL),
        ("cv_compras_arca", "Control compras vs ARCA", CONTROL),
        ("cv_bancos", "Control bancos / cobros", CONTROL),
        ("cv_mercado_pago", "Control Mercado Pago", ("OK", "Pendiente", "Con diferencias", "No corresponde", "A revisar")),
        ("cv_mercado_libre", "Control Mercado Libre", ("OK", "Pendiente", "Con diferencias", "No corresponde", "A revisar")),
        ("cv_observaciones", "Observaciones compras y ventas", "text"),
    )),
    ("Retenciones y percepciones", (
        ("rp_retenciones", "Sufre retenciones", YES_NO_REVIEW),
        ("rp_percepciones", "Sufre percepciones", YES_NO_REVIEW),
        ("rp_ret_iva", "Retenciones IVA", YES_NO_REVIEW),
        ("rp_per_iva", "Percepciones IVA", YES_NO_REVIEW),
        ("rp_ret_gan", "Retenciones Ganancias", YES_NO_REVIEW),
        ("rp_per_gan", "Percepciones Ganancias", YES_NO_REVIEW),
        ("rp_ret_iibb", "Retenciones IIBB", YES_NO_REVIEW),
        ("rp_per_iibb", "Percepciones IIBB", YES_NO_REVIEW),
        ("rp_sircreb", "SIRCREB / deducciones bancarias", ("Sí", "No", "A revisar", "No corresponde")),
        ("rp_observaciones", "Observaciones retenciones y percepciones", "text"),
    )),
    ("Regímenes de información", (
        ("info_posee", "Posee regímenes de información", YES_NO_REVIEW),
        ("info_regimen", "Régimen informativo aplicable", ("multi", "Participaciones societarias", "Bienes registrables", "Facturación electrónica", "Compras y ventas", "Otros regímenes ARCA", "No corresponde", "A revisar")),
        ("info_periodicidad", "Periodicidad", ("Mensual", "Anual", "Eventual", "A requerimiento", "No corresponde")),
        ("info_ultima_presentacion", "Última presentación", "date"),
        ("info_estado", "Estado", ("Presentado", "Pendiente", "Vencido", "No corresponde", "A revisar")),
        ("info_observaciones", "Observaciones", "text"),
    )),
    ("Controles y alertas", (
        ("ctrl_estado", "Estado general", ("OK", "Revisar", "Urgente", "En regularización", "No corresponde")),
        ("ctrl_riesgo", "Riesgo fiscal", ("Bajo", "Medio", "Alto", "Urgente", "Sin evaluar")),
        ("ctrl_ddjj", "DDJJ pendientes", YES_NO_REVIEW),
        ("ctrl_deuda", "Deuda ARCA", ("Sin deuda detectada", "Con deuda", "En plan", "A revisar")),
        ("ctrl_fiscalizaciones", "Fiscalizaciones", YES_NO_REVIEW),
        ("ctrl_intimaciones", "Intimaciones", YES_NO_REVIEW),
        ("ctrl_embargos", "Embargos", YES_NO_REVIEW),
        ("ctrl_planes", "Planes de pago", ("Sí", "No", "Vigente", "Caduco", "A revisar")),
        ("ctrl_observaciones", "Observaciones de control", "text"),
    )),
)
